name: CMWL Pipeline CI

on:
  workflow_run:
    workflows:
      - 'PR Info Check'
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11

      - name: Scalafmt Scalastyle check
        run: sbt check scalastyle

      - name: Check dependencies
        run: sbt clean compile undeclaredCompileDependenciesTest

      - name: Run tests
        run: sbt coverage test coverage it:test

      - name: Upload coverage data to Coveralls
        run: sbt coverageAggregate coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
